"""empty message

Revision ID: 59cbf691966a
Revises: df37e845a2c1
Create Date: 2019-03-12 21:47:39.298656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cbf691966a'
down_revision = 'df37e845a2c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('uploadType', sa.String(), nullable=True))
    op.drop_column('pastes', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pastes', 'uploadType')
    # ### end Alembic commands ###
