"""empty message

Revision ID: df37e845a2c1
Revises: 9afd38cd33ad
Create Date: 2019-03-12 21:45:33.619568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df37e845a2c1'
down_revision = '9afd38cd33ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pastes', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pastes', 'type')
    # ### end Alembic commands ###
